[workspace]

members = [
    "app",
    "socks5",
    "common",
    "transport",
    "settings",
    "vmess",
    "simple_outbounds",
    "router",
    "dns",
    "android_lib"
]

[patch.crates-io]
tokio = { path = "./tokio/tokio" }