[inputs]

[inputs.socks5]
type = "tcp"
port = 8333
[[inputs.socks5.processors]]
type = "socks5_server"
[[inputs.socks5.processors]]
type = "sniffer"
types = ["http"]

[inputs.http]
type = "tcp"
port = 8334
[[inputs.http.processors]]
type = "http_server"
[[inputs.http.processors]]
type = "sniffer"


[routing]

[outputs]
[outputs.direct_tcp]
type = "tcp"
[outputs.direct_udp]
type = "udp"