inbounds:
  socks5:
    pipeline: socks5
    transport:
      type: tcp
      port: 8333

pipelines:
  socks5:
    - type: socks5_proxy_server
    - type: sniffer
      override_dest: true
      types: [tls, http]
