inbounds:
  inbound:
    pipeline: http_in
    transport:
      type: tcp
      port: 8333

pipelines:
  socks5:
    - type: socks5_proxy_server
    - type: associate_uid
    - type: sniffer
      override_dest: true
      types: [tls, http]
  http_in:
    - type: http_proxy_server
    - type: associate_uid
    - type: sniffer
      override_dest: true
      types: [tls, http]

  http_client:
    - type: http_proxy_client
  shadowsocks:
    - type: shadowsocks_client
      password: "barfo"
      method: "aes-256-cfb"
    - type: ssr_client_auth
      user_id: 56256
      protocol: auth_aes128_sha1
    - type: shadowsocks_client_handshake


router:
  defaults:
    tcp: direct_tcp
  rules:
    - target: fiddler
      rule:
        any:
          - dest_domain: ["t.cn"]
          - dest_addr: ["192.168.0.0/16"]

outbounds:
  direct_tcp:
    transport:
      type: tcp
  fiddler:
    pipeline: http_client
    transport:
      type: tcp
      addr: "192.168.1.105"
      port: 8888
  shadowsocks:
    pipeline: shadowsocks
    transport:
      type: tcp
      addr: "127.0.0.1"
      port: 8383

android:
  ports:
    tcp: 10800
    udp: 10801
    dns: 10802
