inbounds:
  inbound_http:
    pipeline: http_in
    transport:
      type: tcp
      port: 8333
  inbound_socks:
    pipeline: socks_in
    transport:
      type: tcp
      port: 8334

pipelines:
  socks_in:
    - type: socks5_proxy_server
    - type: associate_uid
    - type: sniffer
      override_dest: true
      types: [tls, http]
  http_in:
    - type: http_proxy_server
    - type: associate_uid
    - type: sniffer
      override_dest: true
      types: [tls, http]

  http_client:
    - type: http_proxy_client
  shadowsocks:
    - type: ssr_client_obfs
      obfs: http_simple
      port: 8088
      hosts: ['08e7556256.download.windowsupdate.com']
    - type: shadowsocks_client
      password: "ssmu"
      method: "aes-256-cfb"
    - type: ssr_client_auth
      user_id: 56256
      user_key: "******"
      protocol: auth_aes128_md5
    - type: shadowsocks_client_handshake


router:
  defaults:
    tcp: shadowsocks
  rules:
    - target: fiddler
      rule:
        any:
          - dest_domain: ["t.cn"]
          - dest_addr: ["192.168.0.0/16"]

outbounds:
  direct_tcp:
    transport:
      type: tcp
  fiddler:
    pipeline: http_client
    transport:
      type: tcp
      addr: "192.168.1.105"
      port: 8888
  shadowsocks:
    pipeline: shadowsocks
    metering: true
    transport:
      type: tcp
      addr: "47.106.59.183"
      port: 8088
