inbounds:
  inbound_http:
    pipeline: http_in
    transport:
      type: tcp
      port: 8333
  inbound_socks:
    pipeline: socks_in
    transport:
      type: tcp
      port: 8334
  inbound_dns:
    transport:
      type: udp
      port: 8353
  inbound_metrics:
    transport:
      type: tcp
      port: 8300

pipelines:
  socks_in:
    - type: socks5_server
    - type: associate_uid
    # - type: sniffer
    #   override_dest: true
    #   types: [tls, http]
  http_in:
    - type: http_proxy_server
    - type: associate_uid
    # - type: sniffer
    #   override_dest: true
    #   types: [tls, http]

  http_client:
    - type: http_proxy_client
  shadowsocks:
    - type: ssr_obfs_client
      obfs: http_simple
      port: 8088
      hosts: ["7f37f56256.download.windowsupdate.com"]
    - type: ss_stream_cipher_client
      password: "ssmu"
      method: "aes-256-cfb"
    - type: ssr_auth_client
      user_id: 56256
      user_key: "******"
      protocol: auth_aes128_md5
    - type: ss_handshake_client

router:
  defaults:
    tcp: shadowsocks
    udp: direct_udp
  rules:
    - target: fiddler
      rule:
        any:
          - dest_domain: ["t.cn"]
          - dest_addr: ["192.168.0.0/16"]
    - target: metrics
      rule:
        inbound_name: inbound_metrics

outbounds:
  direct_tcp:
    transport:
      type: tcp
  direct_udp:
    transport:
      addr: "223.6.6.6"
      type: udp
      port: 53
  fiddler:
    pipeline: http_client
    transport:
      type: tcp
      addr: "192.168.1.105"
      port: 8888
  shadowsocks:
    pipeline: shadowsocks
    metering: true
    transport:
      type: tcp
      addr: "b4eac403-6eac-4830-b73b-77480dd3cd3d.cz.****"
      port: 8223
  metrics:
    transport:
      type: dashboard
