[package]
name = "comet"
version = "0.1.0"
authors = ["Comet <comet@email.com>"]
edition = "2018"

[dependencies]
# Serde
serde_regex = "1.1.0"
serde_with = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.59"

# Protocol
httparse = "1.3.4"
trust-dns-proto = "0.20"
# http = "0.2.1"
hyper = "0.14.2"
tungstenite = {version = "0.12", default-features = false}
tokio-tungstenite = "0.13"
warp = "0.3"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
tokio-stream = "0.1"
tokio-prepend-io = "0.1.0"

# --
anyhow = "1.0"
log = "0.4"
bytes = "1"
net2 = "0.2.35"
ipnetwork = "0.17.0"
smol_str = { version = "0.1.17", features = ["serde"] }

once_cell = "1.5"
pin-project-lite = "0.2.0"
flurry = "0.3.1"
base64 = "0.13.0"
xorshift = "0.1.3"
url = "2.2.0"
lazy_static = "1.4.0"
lru-cache = "0.1.2"
socket2 = "0.3"
rand = "0.8"

crypto2 = "0.1.1"
shadowsocks-crypto = {version="0.1.2", features = ["v1-stream"]}

[dependencies.regex]
version = "1"
default-features = false
features = ["std", "perf-cache", "perf-dfa"]

[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2.42"
nix = "0.19.0"
pnet = "0.27.2"

[target.'cfg(target_os = "windows")'.dependencies]
cipher = "0.2.1"
hmac = "0.10.1"