[package]
name = "comet"
version = "0.1.0"
authors = ["Comet <comet@email.com>"]
edition = "2018"

[dependencies]
# Serde
serde_regex = "1.1.0"
serde_with = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.59"

# Protocol
httparse = "1.3.4"
trust-dns-proto = "0.20"
# http = "0.2.1"
hyper = "0.14.2"
tungstenite = {version = "0.11.1", default-features = false}
tokio-tungstenite = "0.12.0"
# warp = "0.2"

# Async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1.42"
tokio-compat-02 = "0.2"
tokio-stream = "0.1"

# --
anyhow = "1.0"
log = "0.4.0"

bytes = "1"
net2 = "0.2.35"
ipnetwork = "0.17.0"
smol_str = { version = "0.1.17", features = ["serde"] }

once_cell = "1.5.1"
pin-project-lite = "0.2.0"
flurry = "0.3.1"
base64 = "0.13.0"
xorshift = "0.1.3"
url = "2.2.0"
lazy_static = "1.4.0"
lru-cache = "0.1.2"
socket2 = "0.3.15"


[dependencies.regex]
version = "1"
default-features = false
features = ["std", "perf-cache", "perf-dfa"]

[target.'cfg(not(any(target_os = "android", target_os = "windows")))'.dependencies]
openssl = { version = "0.10" }

[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2.42"
nix = "0.19.0"
pnet = "0.27.2"
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target_os = "windows")'.dependencies]
cipher = "0.2.1"
aes = "0.6.0"
hmac = "0.10.1"
cfb-mode = "0.6.0"
block-modes = "0.7.0"
win-crypto-ng = { git = "https://github.com/chengyuhui/win-crypto-ng", branch = "digest_trait" }