[package]
name = "comet-bin"
version = "0.1.0"
authors = ["Comet <comet@email.com>"]
edition = "2018"

[dependencies]
comet = { path = "../comet" }
env_logger = "0.8"
anyhow = "1.0"
tokio = { version = "0.3.1", features = ["full"] }
log = "0.4.0"