inbounds:
  tcp:
    pipeline: android_tcp
    transport:
      type: tcp
      port: 10800
  dns:
    pipeline: android_dns
    transport:
      type: udp
      port: 10802

pipelines:
  android_tcp:
    - type: android_nat
    - type: sniffer
      override_dest: true
      types: [tls, http]

  android_dns:
    - type: android_nat

  http_client:
    - type: http_proxy_client

router:
  defaults:
    tcp: direct_tcp
    udp: direct_udp
  rules:
    - target: fiddler
      rule:
        any:
          - dest_domain: ["t.cn"]
          - dest_addr: ["192.168.0.0/16"]

outbounds:
  direct_tcp:
    transport:
      type: tcp
  direct_udp:
    transport:
      type: udp
  fiddler:
    pipeline: http_client
    transport:
      type: tcp
      addr: "192.168.1.105"
      port: 8888

android:
  ports:
    tcp: 10800
    udp: 10801
    dns: 10802
