inbounds:
  tcp:
    pipeline: android_tcp
    transport:
      type: tcp
      port: 10800

pipelines:
  android_tcp:
      - type: sniffer
        override_dest: true
        types: [tls, http]
  http_client:
      - type: http_proxy_client

router:
  defaults:
      tcp: direct_tcp
  rules:
      - target: fiddler
        rule:
            any:
              - dest_domain: ["t.cn"]
              - dest_addr: ["192.168.0.0/16"]

outbounds:
  direct_tcp:
      transport:
        type: tcp
  fiddler:
      pipeline: http_client
      transport:
        type: tcp
        addr: "192.168.1.105"
        port: 8888

android:
  ports:
      tcp: 10800
      udp: 10801
      dns: 10802